name: AoE2Taunts
version: 4.0
main: de.kastenklicker.aoe2taunts.AoE2Taunts
author: KastenKlicker
description: An AoE2 Taunts Plugin
commands:

  taunt:
    description: Execute taunts
    usage:   "Use: /taunt <1-105>"

  tauntsorg:
    description: List all original taunts.
    usage: /tauntsorg

  tauntsdef:
    description: List all taunts from the Definitive Edition.
    usage: /tauntsdef